# Generated by Django 4.1.5 on 2023-01-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_subscribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribes',
            new_name='subscribers',
        ),
    ]
